# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20161009_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name'], 'verbose_name': '\u680f\u76ee1', 'verbose_name_plural': '\u680f\u76ee'},
        ),
    ]
