# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:59
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161016_0335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u6587\u7ae0', 'verbose_name_plural': '\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['name'], 'verbose_name': '\u680f\u76ee', 'verbose_name_plural': '\u680f\u76ee'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(max_length=256, unique=False, verbose_name='\u7f51\u5740'),
        ),
    ]
