# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=256, verbose_name='\u7f51\u5740'),
            preserve_default=False,
        ),
    ]
