# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article2',
        ),
        migrations.RenameModel(
            old_name='Column',
            new_name='Column2',
        ),
    ]
