# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20161021_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article2',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Column2',
            new_name='Column',
        ),
    ]
